FROM ubuntu:24.04
# Linux Kernel Build Environment

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libncurses-dev \
    bison \
    flex \
    libssl-dev \
    bc \
    wget \
    python3 \
    ccache \
    curl \
    bsdmainutils \
    libelf-dev \
    cpio
